
import { Video } from './types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Introduction to React Hooks',
    description: 'A comprehensive beginner\'s guide to understanding and using React Hooks like useState, useEffect, and useContext. We cover the basics of functional components and how hooks revolutionize state management in React.',
    thumbnailUrl: 'https://picsum.photos/seed/react/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['react', 'javascript', 'web development', 'frontend'],
    uploader: { name: 'CodeMasters', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d' },
    views: 125000,
    likes: 4500,
    dislikes: 120,
    uploadedAt: '2 months ago',
  },
  {
    id: '2',
    title: 'The Beauty of the Cosmos: Understanding Nebulas',
    description: 'Journey through space as we explore the magnificent structures known as nebulas. Learn about star formation, different types of nebulas, and see stunning images from the James Webb Space Telescope.',
    thumbnailUrl: 'https://picsum.photos/seed/space/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['astronomy', 'space', 'science', 'cosmos'],
    uploader: { name: 'CosmicExplorer', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704e' },
    views: 780000,
    likes: 22000,
    dislikes: 300,
    uploadedAt: '1 year ago',
  },
  {
    id: '3',
    title: 'Python for Data Science in 60 Minutes',
    description: 'A crash course on using Python for data analysis. We will cover popular libraries like Pandas, NumPy, and Matplotlib to manipulate and visualize data effectively.',
    thumbnailUrl: 'https://picsum.photos/seed/python/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['python', 'data science', 'programming', 'machine learning'],
    uploader: { name: 'Data Insights', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704f' },
    views: 450000,
    likes: 15000,
    dislikes: 250,
    uploadedAt: '6 months ago',
  },
  {
    id: '4',
    title: 'The History of Ancient Rome: The Republic',
    description: 'Explore the rise of the Roman Republic, from its mythical founding to its eventual transformation into an empire. We discuss key figures, major wars, and the political structures that defined this era.',
    thumbnailUrl: 'https://picsum.photos/seed/rome/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['history', 'ancient rome', 'education', 'republic'],
    uploader: { name: 'History Buff', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704g' },
    views: 320000,
    likes: 9000,
    dislikes: 150,
    uploadedAt: '3 months ago',
  },
  {
    id: '5',
    title: 'Fundamentals of Graphic Design',
    description: 'Learn the core principles of graphic design, including color theory, typography, layout, and composition. This video is perfect for beginners looking to start their creative journey.',
    thumbnailUrl: 'https://picsum.photos/seed/design/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['graphic design', 'art', 'tutorial', 'creative'],
    uploader: { name: 'Creative Fuel', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704h' },
    views: 95000,
    likes: 6000,
    dislikes: 80,
    uploadedAt: '5 days ago',
  },
    {
    id: '6',
    title: 'Mastering Chess Openings: The Sicilian Defense',
    description: 'A deep dive into one of the most popular and aggressive chess openings for Black. Learn the main variations, key ideas, and common traps of the Sicilian Defense to improve your game.',
    thumbnailUrl: 'https://picsum.photos/seed/chess/640/360',
    videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    tags: ['chess', 'strategy', 'games', 'education'],
    uploader: { name: 'Grandmaster Insights', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704i' },
    views: 180000,
    likes: 8500,
    dislikes: 110,
    uploadedAt: '1 month ago',
  },
];
